version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=iventou
    volumes:
      - postgresql_data:/bitnami/postgresql

  backend:
    build: .
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://docker:docker@postgresql:5432/iventou
      - NODE_ENV=production
    depends_on:
      - postgresql

volumes:
  postgresql_data:
