version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=iventou
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
